package godot

import (
	"github.com/gabstv/godot-go/gdnative"
)

/*------------------------------------------------------------------------------
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated. Any updates should be done in
//   "class.go.tmpl" so they can be included in the generated
//   code.
//----------------------------------------------------------------------------*/

//func NewCheckBoxFromPointer(ptr gdnative.Pointer) CheckBox {
func newCheckBoxFromPointer(ptr gdnative.Pointer) CheckBox {
	owner := gdnative.NewObjectFromPointer(ptr)
	obj := CheckBox{}
	obj.SetBaseObject(owner)

	return obj
}

/*
A checkbox allows the user to make a binary choice (choosing only one of two possible options). It's similar to [CheckButton] in functionality, but it has a different appearance. To follow established UX patterns, it's recommended to use CheckBox when toggling it has [b]no[/b] immediate effect on something. For instance, it should be used when toggling it will only do something once a confirmation button is pressed.
*/
type CheckBox struct {
	Button
	owner gdnative.Object
}

func (o *CheckBox) BaseClass() string {
	return "CheckBox"
}

// CheckBoxImplementer is an interface that implements the methods
// of the CheckBox class.
type CheckBoxImplementer interface {
	ButtonImplementer
}
