package godot

import (
	"github.com/gabstv/godot-go/gdnative"
)

/*------------------------------------------------------------------------------
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated. Any updates should be done in
//   "class.go.tmpl" so they can be included in the generated
//   code.
//----------------------------------------------------------------------------*/

//func NewPopupDialogFromPointer(ptr gdnative.Pointer) PopupDialog {
func newPopupDialogFromPointer(ptr gdnative.Pointer) PopupDialog {
	owner := gdnative.NewObjectFromPointer(ptr)
	obj := PopupDialog{}
	obj.SetBaseObject(owner)

	return obj
}

/*
Undocumented
*/
type PopupDialog struct {
	Popup
	owner gdnative.Object
}

func (o *PopupDialog) BaseClass() string {
	return "PopupDialog"
}

// PopupDialogImplementer is an interface that implements the methods
// of the PopupDialog class.
type PopupDialogImplementer interface {
	PopupImplementer
}
