package godot

import (
	"github.com/gabstv/godot-go/gdnative"
)

/*------------------------------------------------------------------------------
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated. Any updates should be done in
//   "class.go.tmpl" so they can be included in the generated
//   code.
//----------------------------------------------------------------------------*/

//func NewToolButtonFromPointer(ptr gdnative.Pointer) ToolButton {
func newToolButtonFromPointer(ptr gdnative.Pointer) ToolButton {
	owner := gdnative.NewObjectFromPointer(ptr)
	obj := ToolButton{}
	obj.SetBaseObject(owner)

	return obj
}

/*
Undocumented
*/
type ToolButton struct {
	Button
	owner gdnative.Object
}

func (o *ToolButton) BaseClass() string {
	return "ToolButton"
}

// ToolButtonImplementer is an interface that implements the methods
// of the ToolButton class.
type ToolButtonImplementer interface {
	ButtonImplementer
}
