package godot

import (
	"github.com/gabstv/godot-go/gdnative"
)

/*------------------------------------------------------------------------------
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated. Any updates should be done in
//   "class.go.tmpl" so they can be included in the generated
//   code.
//----------------------------------------------------------------------------*/

//func NewVisualShaderNodeVectorClampFromPointer(ptr gdnative.Pointer) VisualShaderNodeVectorClamp {
func newVisualShaderNodeVectorClampFromPointer(ptr gdnative.Pointer) VisualShaderNodeVectorClamp {
	owner := gdnative.NewObjectFromPointer(ptr)
	obj := VisualShaderNodeVectorClamp{}
	obj.SetBaseObject(owner)

	return obj
}

/*
Constrains a value to lie between [code]min[/code] and [code]max[/code] values. The operation is performed on each component of the vector individually.
*/
type VisualShaderNodeVectorClamp struct {
	VisualShaderNode
	owner gdnative.Object
}

func (o *VisualShaderNodeVectorClamp) BaseClass() string {
	return "VisualShaderNodeVectorClamp"
}

// VisualShaderNodeVectorClampImplementer is an interface that implements the methods
// of the VisualShaderNodeVectorClamp class.
type VisualShaderNodeVectorClampImplementer interface {
	VisualShaderNodeImplementer
}
