package godot

import (
	"github.com/gabstv/godot-go/gdnative"
)

/*------------------------------------------------------------------------------
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated. Any updates should be done in
//   "class.go.tmpl" so they can be included in the generated
//   code.
//----------------------------------------------------------------------------*/

//func NewVisualShaderNodeFresnelFromPointer(ptr gdnative.Pointer) VisualShaderNodeFresnel {
func newVisualShaderNodeFresnelFromPointer(ptr gdnative.Pointer) VisualShaderNodeFresnel {
	owner := gdnative.NewObjectFromPointer(ptr)
	obj := VisualShaderNodeFresnel{}
	obj.SetBaseObject(owner)

	return obj
}

/*
Returns falloff based on the dot product of surface normal and view direction of camera (pass associated inputs to it).
*/
type VisualShaderNodeFresnel struct {
	VisualShaderNode
	owner gdnative.Object
}

func (o *VisualShaderNodeFresnel) BaseClass() string {
	return "VisualShaderNodeFresnel"
}

// VisualShaderNodeFresnelImplementer is an interface that implements the methods
// of the VisualShaderNodeFresnel class.
type VisualShaderNodeFresnelImplementer interface {
	VisualShaderNodeImplementer
}
