package godot

import (
	"github.com/gabstv/godot-go/gdnative"
)

/*------------------------------------------------------------------------------
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated. Any updates should be done in
//   "class.go.tmpl" so they can be included in the generated
//   code.
//----------------------------------------------------------------------------*/

//func NewVisualShaderNodeIfFromPointer(ptr gdnative.Pointer) VisualShaderNodeIf {
func newVisualShaderNodeIfFromPointer(ptr gdnative.Pointer) VisualShaderNodeIf {
	owner := gdnative.NewObjectFromPointer(ptr)
	obj := VisualShaderNodeIf{}
	obj.SetBaseObject(owner)

	return obj
}

/*
First two ports are scalar floatin-point numbers to compare, third is tolerance comparison amount and last three ports represents a vectors returned if [code]a == b[/code], [code]a > b[/code] and [code]a < b[/code] respectively.
*/
type VisualShaderNodeIf struct {
	VisualShaderNode
	owner gdnative.Object
}

func (o *VisualShaderNodeIf) BaseClass() string {
	return "VisualShaderNodeIf"
}

// VisualShaderNodeIfImplementer is an interface that implements the methods
// of the VisualShaderNodeIf class.
type VisualShaderNodeIfImplementer interface {
	VisualShaderNodeImplementer
}
